[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["cleanwasm"]

[tasks.cleanwasm]
command = "rm"
args = ["-rf", "./pkg"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.testrs]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.testjs]
command = "node"
args = ["--test", "./test"]
dependencies = ["clean"]

[tasks.test]
dependencies = ["testrs", "testjs"]

[tasks.wasm]
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--scope", "platformatic", "--release"]
dependencies = ["clean"]

[tasks.build]
command = "node"
args = ["./tools/build.js"]
dependencies = ["wasm"]

[tasks.publish]
command = "wasm-pack"
args = ["publish"]
dependencies = ["wasm"]
