[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["cleanwasm"]

[tasks.cleanwasm]
command = "rm"
args = ["-rf", "./pkg"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.testrs]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.testjs]
command = "node"
args = ["--test", "./test/index.test.js"]
dependencies = ["clean", "wasm"]

[tasks.test]
dependencies = ["wasm", "testrs", "testjs"]

[tasks.wasm]
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--scope", "platformatic", "--release", "--no-opt"]
dependencies = ["clean", "format", "lint"]

[tasks.build]
dependencies = ["test", "wasm"]

[tasks.publish]
command = "wasm-pack"
args = ["publish"]
dependencies = ["build"]

[tasks.default]
alias = "test"
