name: run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Install cargo make
        run: cargo install make
      - name: build wasm
        run: cargo make wasm
      - name: lint check
        run: cargo make lint
      - name: Run test suite
        run: cargo make test
