name: run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: build wasm
        run: cargo make wasm
      - name: lint check
        run: cargo make lint
      - name: Run test suite
        run: cargo make test
